// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using timan.api.Models;

namespace timan.api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("timan.models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Giày da nam"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Giày thể thao nữ"
                        });
                });

            modelBuilder.Entity("timan.models.ProductList", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Desc1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int>("Sold")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.ToTable("productLists");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 1,
                            Desc1 = "Hỗ trợ đổi size miễn phí",
                            Desc2 = "Bảo hành từ 1 đến 5 năm",
                            Desc3 = "Giao hàng nhanh toàn quốc",
                            Desc4 = "Bộ sản phẩm bao gồm: Hộp, Giấy Lót, Thẻ Bảo Hành, Thẻ Hướng Dẫn Bảo Quản",
                            Photo = "images/giaydanam.png",
                            Price = "550.038",
                            ProductName = "Giày Da Nam Đế Bằng MH19",
                            Rate = 342,
                            Sold = 432,
                            Status = "Còn hàng"
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 2,
                            Desc1 = "Hỗ trợ đổi size miễn phí",
                            Desc2 = "Bảo hành từ 1 đến 5 năm",
                            Desc3 = "Giao hàng nhanh toàn quốc",
                            Desc4 = "Bộ sản phẩm bao gồm: Hộp, Giấy Lót, Thẻ Bảo Hành, Thẻ Hướng Dẫn Bảo Quản",
                            Photo = "images/giaythethonu.jpg",
                            Price = "550.038",
                            ProductName = "Giày thể thao nữ",
                            Rate = 283,
                            Sold = 533,
                            Status = "Còn hàng"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
